# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74e107114a27fb3e3ae6261d9af64393db74b52962d75c25402cc89e668a3498e54caa0cca4c7c1bd5a02967909e27e75ea4115b5d940ec8f995a857cea72566

test:
  secret_key_base: b3ae5b82780dd806b1e08a0d8eba3391d5fc8d991e9898cedcc56bf310b46b72209b95c4d9c7acbbe08a0243686af4cd6729af678c8dd717fcc0b2a3b8b7f3df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
